---
version: '3.8'

networks:
  k6:

services:
  prometheus:
    image: prom/prometheus:v2.46.0
    platform: linux/amd64
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - k6
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.2
    platform: linux/amd64
    networks:
      - k6
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    container_name: k6-prom
    image: dukecyber/k6-prom:v0.2.3-alpine3.18
    networks:
      - k6
    ports:
      - "6565:6565"
    command: ["run", "/scripts/test-k6.js"]
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
      - K6_OUT=xk6-prometheus-rw
    depends_on:
      - prometheus
    volumes:
      - ../../examples:/scripts